export const LOGIN = "LOGIN";
export const PROFILE = "PROFILE";
export const MODAL_SET_PASSWORD_SHOW = "MODAL_SET_PASSWORD_SHOW";
export const MODAL_SET_PASSWORD_HIDDEN = "MODAL_SET_PASSWORD_HIDDEN";

// ANTRIAN
export const ANTRIAN_GET_DATA = "ANTRIAN_GET_DATA";

//UPDATE_PAGE
export const UPDATE_PAGE = "UPDATE_PAGE";
export const STOP_PAGE = "STOP_PAGE";

// BOOKING
export const BOOKING_GET_DATA = "BOOKING_GET_DATA";
export const BOOKING_DETAIL = "BOOKING_DETAIL";
export const BOOKING_MODAL_SHOW = "BOOKING_MODAL_SHOW";
export const BOOKING_MODAL_HIDDEN = "BOOKING_MODAL_HIDDEN";
export const BOOKING_BATAL = "BOOKING_BATAL";
export const BOOKING_BATAL_SHOW = "BOOKING_BATAL_SHOW";
export const BOOKING_BATAL_HIDDEN = "BOOKING_BATAL_HIDDEN";
